######################## Documentation ########################
# Dokumentasi hitpoint API ini bisa dijalankan menggunakan
# ekstensi dari teks editor VScode yaitu Rest Client.
# Kebanyakan hitpoint hanya bisa diakses setelah melakukan login
# untuk itu harap isi terlebih dahulu database atau jalankan
# perintah seeder yang ada.
#
# Berikut hit poin yang bisa diakses tanpa login
# - Register
# - get all user
######################## Auth Hit Point #######################

### register ###
# dalam kasus ini sebaiknya tidak menggunakan register
# karna login menggunakan beberapa level akses
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "nama": "awe",
    "nip": "423443221",
    "email": "add@mail.com",
    "alamat": "asddffsd",
    "no_tlp": "081208193",
    "levelID": 2,
    "departmentID": 3,
    "password": "123123123",
    "confpassword": "123123123"
}

### login ###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "add@mail.com",
    "password": "123123123"
}

### generate token untuk "remember" jika akses setelah login  ###
GET   http://localhost:3000/auth/token

### logout ###
DELETE  http://localhost:3000/auth/logout







######################## Level Hit Point #######################

### get all level data ###
GET http://localhost:3000/level
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoiYWRkQG1haWwuY29tIiwiaWF0IjoxNjkwNDYwNzY1LCJleHAiOjE2OTA0NjQzNjV9.fAP_MTHWFgn1JJYc37AbXxHz0BMmo1mcmVRY2toTbUA

### get level by id ###
GET http://localhost:3000/level/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoiYWRkQG1haWwuY29tIiwiaWF0IjoxNjkwNDYwNzY1LCJleHAiOjE2OTA0NjQzNjV9.fAP_MTHWFgn1JJYc37AbXxHz0BMmo1mcmVRY2toTbUA

### Create level ###
POST http://localhost:3000/level
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoiYWRkQG1haWwuY29tIiwiaWF0IjoxNjkwNDYwNzY1LCJleHAiOjE2OTA0NjQzNjV9.fAP_MTHWFgn1JJYc37AbXxHz0BMmo1mcmVRY2toTbUA

{
    "levelName": "Oprator"
}

### Edit level ###
POST http://localhost:3000/level/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoiYWRkQG1haWwuY29tIiwiaWF0IjoxNjkwNDYwNzY1LCJleHAiOjE2OTA0NjQzNjV9.fAP_MTHWFgn1JJYc37AbXxHz0BMmo1mcmVRY2toTbUA

{
    "levelName": "Staff"
}

### Delete level ###
DELETE  http://localhost:3000/level/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoiYWRkQG1haWwuY29tIiwiaWF0IjoxNjkwNDYwNzY1LCJleHAiOjE2OTA0NjQzNjV9.fAP_MTHWFgn1JJYc37AbXxHz0BMmo1mcmVRY2toTbUA









######################## Department Hit Point #######################

### get all department data ###
GET http://localhost:3000/department
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoiYWRkQG1haWwuY29tIiwiaWF0IjoxNjkwNDYwNzY1LCJleHAiOjE2OTA0NjQzNjV9.fAP_MTHWFgn1JJYc37AbXxHz0BMmo1mcmVRY2toTbUA

### get department by id ###
GET http://localhost:3000/department/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoiYWRkQG1haWwuY29tIiwiaWF0IjoxNjkwNDYwNzY1LCJleHAiOjE2OTA0NjQzNjV9.fAP_MTHWFgn1JJYc37AbXxHz0BMmo1mcmVRY2toTbUA

### Create department ###
POST http://localhost:3000/department
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoiYWRkQG1haWwuY29tIiwiaWF0IjoxNjkwNDYwNzY1LCJleHAiOjE2OTA0NjQzNjV9.fAP_MTHWFgn1JJYc37AbXxHz0BMmo1mcmVRY2toTbUA

{
    "departmentName": "Accounting"
}

### Edit department ###
POST http://localhost:3000/department/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoiYWRkQG1haWwuY29tIiwiaWF0IjoxNjkwNDYwNzY1LCJleHAiOjE2OTA0NjQzNjV9.fAP_MTHWFgn1JJYc37AbXxHz0BMmo1mcmVRY2toTbUA

{
    "departmentName": "Human Resource"
}

### Delete department ###
DELETE  http://localhost:3000/department/9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoiYWRkQG1haWwuY29tIiwiaWF0IjoxNjkwNDYwNzY1LCJleHAiOjE2OTA0NjQzNjV9.fAP_MTHWFgn1JJYc37AbXxHz0BMmo1mcmVRY2toTbUA






######################## User Hit Point #######################

### get all user data ###
GET http://localhost:3000/users


### get user by id ###
GET http://localhost:3000/users/2

### Create user ###
POST http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoiYWRkQG1haWwuY29tIiwiaWF0IjoxNjkwNDYwNzY1LCJleHAiOjE2OTA0NjQzNjV9.fAP_MTHWFgn1JJYc37AbXxHz0BMmo1mcmVRY2toTbUA

{
    "nama": "anaba",
    "nip": "32123123",
    "email": "a@mail.com",
    "alamat": "sddfsd",
    "no_tlp": "08271266",
    "levelID": 1,
    "departmentID": 6,
    "password": "123123123",
    "confpassword": "123123123"
}


### Edit user ###
POST http://localhost:3000/users/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoiYWRkQG1haWwuY29tIiwiaWF0IjoxNjkwNDYwNzY1LCJleHAiOjE2OTA0NjQzNjV9.fAP_MTHWFgn1JJYc37AbXxHz0BMmo1mcmVRY2toTbUA

{
    "nama": "amawa",
    "levelID": 3
}


### Delete user ###
DELETE  http://localhost:3000/users/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoiYWRkQG1haWwuY29tIiwiaWF0IjoxNjkwNDYwNzY1LCJleHAiOjE2OTA0NjQzNjV9.fAP_MTHWFgn1JJYc37AbXxHz0BMmo1mcmVRY2toTbUA